# Generated by Django 3.2.5 on 2021-09-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecontent',
            name='Count',
            field=models.IntegerField(),
        ),
    ]
