# Generated by Django 3.2.5 on 2021-09-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storeaddproduct_storebuyproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
